name: thembrehms
favicon: null
layout_spectrum: 0.6086877803318202
typography_spectrum: 0.50167
title: Them Brehms and their doings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#142b75'
    - '#51473e'
    - '#cbdba8'
    - '#a1715b'
    - '#97a999'
  brandStrength: 0.0578922766726464
  lightness: 0.9964323884341866
  saturation: 0.7713522997219115
  rhythmicContrast: 0.10238760989159346
purpose: []
